set lib name to "hwloc" (vs. implied "hwloc2") in manifest
Currently the tests and examples will not compile because they include...

  extern crate hwloc;

but the package name is hwloc2, not hwloc:

error[E0463]: can't find crate for `hwloc`
 --> examples/bind_threads.rs:1:1
  |
1 | extern crate hwloc;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

this fixes the issue by setting the lib name o "hwloc" in the Cargo.toml
manifest, allowing cargo/rustc to identify the "hwloc" reference in the
tests and examples.